language: node_js
node_js:
  - "0.10"

branches:
  only:
    - master

env:
  global:
    - secure: hD9O8NEni8jWuuC0/7ff92/lFMZfMUBqBfUspKOXuychqluAKV1eZxaJ6rkQDVhXC+Ee37uGeJtaVcS+Jf0ZAfzb9/eBNolnTcLqfNiXJujXKRC2I6y+tHYLy/c5vI4oyhwD55ZVm+ZKVrjjukz1Ti7xd6+e+mW26QLLsQ9cgEg=
    - secure: nlmfpXSQo6/ihXay2/WYjAlL69mCDzch0rODrCUsHufajI/P9AJAEl4TduYj78NvV97qFHBZ4Kec0UAWVYoKZLG5CALe9tNlvSqxrBM0WpDd4MACfAAx6fkLC+/GIKPcW5fTwO/t4ztTI1GJsxRCjIDSi3SOlYJ+PaA2e4U81x4=

before_install:
  # Add extra apt repos
  - echo "deb http://debian.datastax.com/community stable main" | sudo tee -a /etc/apt/sources.list.d/dsc.sources.list
  - curl -L http://debian.datastax.com/debian/repo_key | sudo apt-key add -
  - echo 'yes' | sudo add-apt-repository ppa:oae/deps
  - echo 'yes' | sudo add-apt-repository ppa:coolwanglu/pdf2htmlex
  - sudo apt-get update

  # Install cassandra 1.2 manually
  - sudo apt-get install -y -o Dpkg::Options::=--force-confnew cassandra=1.2.15 dsc12
  - sudo sed -i 's/-Xss180k/-Xss256k/g' /etc/cassandra/cassandra-env.sh
  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /etc/cassandra/cassandra-env.sh"
  - sudo service cassandra stop
  - sudo service cassandra start
  - sudo service cassandra status

  # Turn off unneeded services to free some memory
  - sudo service mysql stop
  - sudo service memcached stop
  - sudo service postgresql stop

  # Install Hilary deps
  - sudo apt-get install -qq graphicsmagick libreoffice pdftk chrpath pdf2htmlex
  - npm install -g grunt-cli
  - git clone --depth 1 --branch master git://github.com/oaeproject/3akai-ux.git ../3akai-ux

  # Install etherpad-lite
  - sudo apt-get install etherpad-lite
  - cd /opt/etherpad
  - sudo touch APIKEY.txt
  - sudo chmod -R 777 .
  - "sed -i 's/defaultPadText\" : \".*\"/defaultPadText\" : \"\"/g' settings.json"
  - echo "13SirapH8t3kxUh5T5aqWXhXahMzoZRA" > APIKEY.txt
  - node src/node/server.js &> /dev/null &

  # Position ourselves to start the test in "script" phase
  - cd ~/build/oaeproject/Hilary

  # Enable preview processing
  - printf "\n\nconfig.previews.enabled = true;" >> config.js
  - printf "\nconfig.previews.office.binary = '/usr/bin/soffice';" >> config.js
  - printf "\nconfig.previews.pdftk.binary = '/usr/bin/pdftk';" >> config.js
  - printf "\nconfig.previews.pdf2htmlEX.binary = '/usr/bin/pdf2htmlEX';" >> config.js

services:
  - elasticsearch
  - rabbitmq
  - redis-server

script:
  - grunt test-coverage-coveralls

after_success:
  # Package and upload to Amazon S3, but only if we're building on code that is merged into master
  - git reset --hard origin/master
  - git checkout master
  - npm shrinkwrap
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bin/package -su --upload-bucket=oae-releases-travis; fi

after_failure:
  - cat tests.log | node_modules/.bin/bunyan -l info

notifications:
  email:
    - oae-team@collab.sakaiproject.org
  irc: "irc.freenode.org#oae"
